version: '3'
services:
  database:
    image: postgres:13
    container_name: ms-database
    restart: always
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_DB=postgres'